package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"strings"

	"github.com/gmcorenet/framework/routing/annotations"
)

type discoveredAnnotation struct {
	Name    string
	Target  annotations.AnnotationTarget
	Args    map[string]string
	Context string
}

func main() {
	sourceDir := "internal/controller"
	outDir := "internal/generated"
	module := "github.com/gmcorenet/skeleton"
	if len(os.Args) > 1 {
		sourceDir = os.Args[1]
	}
	if len(os.Args) > 2 {
		outDir = os.Args[2]
	}
	if len(os.Args) > 3 {
		module = os.Args[3]
	}

	anns, structs := scan(sourceDir)
	os.MkdirAll(outDir, 0755)

	generateRegister(outDir, module, structs)
	generateRoutes(outDir, module, anns)
	generateRateLimits(outDir, module, anns)
	generateSubscribers(outDir, module, anns)
	generateSecurity(outDir, module, anns)
	generateCaches(outDir, module, anns)
	generateValidators(outDir, module, anns)
	generateTemplates(outDir, module, anns)

	imports := readServicesYAML("config/services.yaml")
	if len(imports) > 0 {
		generateServices(outDir, module, imports)

		total := 0
		total += len(structs)
		total += len(imports)
		for _, a := range anns {
			switch a.Name {
			case "Route", "RateLimit", "Subscribe":
				total++
			}
		}
		fmt.Printf("Generated %d controller(s), %d service(s), %d annotation(s) in %s/\n",
			len(structs), len(imports), len(anns), outDir)
		return
	}

	routeCount, rateCount, subCount := countAnnotations(anns)
	fmt.Printf("Generated %d controller(s), %d route(s), %d ratelimit(s), %d subscriber(s) in %s/\n",
		len(structs), routeCount, rateCount, subCount, outDir)
}

func countAnnotations(anns []discoveredAnnotation) (routes, rates, subs int) {
	for _, a := range anns {
		switch a.Name {
		case "Route":
			routes++
		case "RateLimit":
			rates++
		case "Subscribe":
			subs++
		}
	}
	return
}

func generateRegister(outDir, module string, structs []string) {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by gmcore; DO NOT EDIT.\n\n")
	buf.WriteString("package generated\n\n")
	buf.WriteString("import (\n")
	buf.WriteString("\t\"github.com/gmcorenet/framework/routing\"\n")
	buf.WriteString(fmt.Sprintf("\t_controller \"%s/internal/controller\"\n", module))
	buf.WriteString(")\n\n")
	buf.WriteString("func init() {\n")
	for _, s := range structs {
		buf.WriteString(fmt.Sprintf("\trouting.Register(func() interface{} { return &_controller.%s{} })\n", s))
	}
	buf.WriteString("}\n")
	writeGo(outDir+"/register_gen.go", buf.Bytes())
}

func generateRoutes(outDir, module string, anns []discoveredAnnotation) {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by gmcore; DO NOT EDIT.\n\n")
	buf.WriteString("package generated\n\n")
	buf.WriteString("import (\n")
	buf.WriteString("\t\"github.com/gmcorenet/framework/container\"\n")
	buf.WriteString("\t\"github.com/gmcorenet/framework/router\"\n")
	buf.WriteString("\t\"github.com/gmcorenet/framework/routing\"\n")
	buf.WriteString(")\n\n")

	buf.WriteString("func RegisterGeneratedRoutes(r *router.Router, c *container.Container) []map[string]interface{} {\n")
	buf.WriteString("\tvar exposed []map[string]interface{}\n\n")

	hasRoutes := false
	for _, a := range anns {
		if a.Name != "Route" || a.Context != "method" {
			continue
		}
		hasRoutes = true
		sid := annotations.TypeToServiceID(a.Target.StructName)
		methodsRaw := a.Args["methods"]
		if methodsRaw == "" {
			methodsRaw = "GET"
		}
		methods := annotations.SplitList(methodsRaw)
		name := a.Args["name"]
		if name == "" {
			name = sid + "_" + strings.ToLower(a.Target.MethodName)
		}
		isPublic := a.Args["public"] == "true"

		buf.WriteString(fmt.Sprintf("\tif svc, err := c.Get(%q); err == nil {\n", sid))
		buf.WriteString(fmt.Sprintf("\t\troute, _ := r.Handle(%q, %s, routing.MakeHandler(svc, %q))\n",
			convertPath(a.Args["path"]), formatSlice(methods), a.Target.MethodName))
		buf.WriteString(fmt.Sprintf("\t\troute.Name = %q\n", name))
		if isPublic {
			buf.WriteString(fmt.Sprintf("\t\texposed = append(exposed, map[string]interface{}{\"name\":%q,\"path\":%q,\"methods\":%s})\n",
				name, a.Args["path"], formatSlice(methods)))
		}
		buf.WriteString("\t}\n\n")
	}

	buf.WriteString("\treturn exposed\n")
	buf.WriteString("}\n")

	if hasRoutes {
		writeGo(outDir+"/routes_gen.go", buf.Bytes())
	}
}

func generateRateLimits(outDir, module string, anns []discoveredAnnotation) {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by gmcore; DO NOT EDIT.\n\n")
	buf.WriteString("package generated\n\n")
	buf.WriteString("import \"github.com/gmcorenet/framework/container\"\n\n")

	buf.WriteString("func RegisterGeneratedRateLimits(c *container.Container) {\n")
	for _, a := range anns {
		if a.Name != "RateLimit" || a.Context != "method" {
			continue
		}
		sid := annotations.TypeToServiceID(a.Target.StructName)
		key := a.Args["key"]
		max := a.Args["max"]
		per := a.Args["per"]

		if key != "" {
			buf.WriteString(fmt.Sprintf("\tc.Set(\"ratelimit.%s.%s\", map[string]interface{}{\"key\":%q})\n",
				sid, a.Target.MethodName, key))
		} else if max != "" {
			buf.WriteString(fmt.Sprintf("\tc.Set(\"ratelimit.%s.%s\", map[string]interface{}{\"max\":%s,\"per\":%q})\n",
				sid, a.Target.MethodName, max, per))
		}
	}
	buf.WriteString("}\n")
	writeGo(outDir+"/ratelimits_gen.go", buf.Bytes())
}

func generateSecurity(outDir, module string, anns []discoveredAnnotation) {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by gmcore; DO NOT EDIT.\n\n")
	buf.WriteString("package generated\n\n")
	buf.WriteString("import \"github.com/gmcorenet/framework/container\"\n\n")
	buf.WriteString("func RegisterGeneratedSecurity(c *container.Container) {\n")
	for _, a := range anns {
		if a.Name != "Security" || a.Context != "method" {
			continue
		}
		sid := annotations.TypeToServiceID(a.Target.StructName)
		role := a.Args["role"]
		roles := a.Args["roles"]
		strategy := a.Args["strategy"]
		key := a.Args["key"]

		if role == "" && roles == "" && key == "" {
			continue
		}

		parts := []string{}
		if role != "" {
			parts = append(parts, fmt.Sprintf("\"role\":%q", role))
		}
		if roles != "" {
			parts = append(parts, fmt.Sprintf("\"roles\":[]string{%s}", formatRoles(roles)))
		}
		if strategy != "" {
			parts = append(parts, fmt.Sprintf("\"strategy\":%q", strategy))
		}
		if key != "" {
			parts = append(parts, fmt.Sprintf("\"key\":%q", key))
		}

		buf.WriteString(fmt.Sprintf("\tc.Set(\"security.%s.%s\", map[string]interface{}{%s})\n",
			sid, a.Target.MethodName, strings.Join(parts, ", ")))
	}
	buf.WriteString("}\n")

	buf.WriteString("\nfunc RegisterSecurityRouteMap(c *container.Container) {\n")
	buf.WriteString("\trouteMap := map[string]map[string]interface{}{\n")
	for _, a := range anns {
		if a.Name != "Route" || a.Context != "method" {
			continue
		}
		sid := annotations.TypeToServiceID(a.Target.StructName)
		buf.WriteString(fmt.Sprintf("\t\t%q: {\"controller\":%q,\"action\":%q},\n",
			a.Args["path"], sid, a.Target.MethodName))
	}
	buf.WriteString("\t}\n")
	buf.WriteString("\tc.Set(\"security.route_map\", routeMap)\n")
	buf.WriteString("}\n")

	writeGo(outDir+"/security_gen.go", buf.Bytes())
}

func generateCaches(outDir, module string, anns []discoveredAnnotation) {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by gmcore; DO NOT EDIT.\n\n")
	buf.WriteString("package generated\n\n")
	buf.WriteString("import \"github.com/gmcorenet/framework/container\"\n\n")
	buf.WriteString("func RegisterGeneratedCaches(c *container.Container) {\n")
	for _, a := range anns {
		if a.Name != "Cache" || a.Context != "method" {
			continue
		}
		sid := annotations.TypeToServiceID(a.Target.StructName)
		ttl := a.Args["ttl"]
		key := a.Args["key"]
		if ttl == "" && key == "" {
			continue
		}
		buf.WriteString(fmt.Sprintf("\tc.Set(\"cache.%s.%s\", map[string]interface{}{\"ttl\":%s,\"key\":%q})\n",
			sid, a.Target.MethodName, ttl, key))
	}
	buf.WriteString("}\n")
	writeGo(outDir+"/caches_gen.go", buf.Bytes())
}

func generateValidators(outDir, module string, anns []discoveredAnnotation) {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by gmcore; DO NOT EDIT.\n\n")
	buf.WriteString("package generated\n\n")
	buf.WriteString("import \"github.com/gmcorenet/framework/container\"\n\n")
	buf.WriteString("func RegisterGeneratedValidators(c *container.Container) {\n")
	for _, a := range anns {
		if a.Name != "Validate" || a.Context != "method" {
			continue
		}
		sid := annotations.TypeToServiceID(a.Target.StructName)
		rules := a.Args["rules"]
		groups := a.Args["groups"]
		if rules == "" {
			continue
		}
		buf.WriteString(fmt.Sprintf("\tc.Set(\"validate.%s.%s\", map[string]interface{}{\"rules\":%q,\"groups\":%q})\n",
			sid, a.Target.MethodName, rules, groups))
	}
	buf.WriteString("}\n")
	writeGo(outDir+"/validators_gen.go", buf.Bytes())
}

func generateTemplates(outDir, module string, anns []discoveredAnnotation) {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by gmcore; DO NOT EDIT.\n\n")
	buf.WriteString("package generated\n\n")
	buf.WriteString("import \"github.com/gmcorenet/framework/container\"\n\n")
	buf.WriteString("func RegisterGeneratedTemplates(c *container.Container) {\n")
	for _, a := range anns {
		if a.Name != "Template" || a.Context != "method" {
			continue
		}
		sid := annotations.TypeToServiceID(a.Target.StructName)
		tmpl := a.Args["template"]
		if tmpl == "" {
			continue
		}
		buf.WriteString(fmt.Sprintf("\tc.Set(\"template.%s.%s\", map[string]interface{}{\"template\":%q})\n",
			sid, a.Target.MethodName, tmpl))
	}
	buf.WriteString("}\n")
	writeGo(outDir+"/templates_gen.go", buf.Bytes())
}

func generateSubscribers(outDir, module string, anns []discoveredAnnotation) {
	hasSubs := false
	for _, a := range anns {
		if a.Name == "Subscribe" && a.Context == "method" && a.Args["event"] != "" {
			hasSubs = true
			break
		}
	}
	if !hasSubs {
		return
	}
	var buf bytes.Buffer
	buf.WriteString("// Code generated by gmcore; DO NOT EDIT.\n\n")
	buf.WriteString("package generated\n\n")
	buf.WriteString("import (\n")
	buf.WriteString("\t\"github.com/gmcorenet/framework/container\"\n")
	buf.WriteString("\t\"github.com/gmcorenet/framework/events\"\n")
	buf.WriteString(")\n\n")

	buf.WriteString("func RegisterGeneratedSubscribers(c *container.Container) {\n")
	for _, a := range anns {
		if a.Name != "Subscribe" || a.Context != "method" {
			continue
		}
		sid := annotations.TypeToServiceID(a.Target.StructName)
		event := a.Args["event"]
		if event == "" {
			continue
		}

		buf.WriteString(fmt.Sprintf("\tif svc, err := c.Get(%q); err == nil {\n", sid))
		buf.WriteString(fmt.Sprintf("\t\tif disp, ok := c.Get(\"dispatcher\"); ok {\n"))
		buf.WriteString(fmt.Sprintf("\t\t\tif bus, ok := disp.(events.EventDispatcher); ok {\n"))
		buf.WriteString(fmt.Sprintf("\t\t\t\tbus.Subscribe(%q, events.WrapListener(svc, %q))\n", event, a.Target.MethodName))
		buf.WriteString("\t\t\t}\n\t\t}\n\t}\n\n")
	}
	buf.WriteString("}\n")
	writeGo(outDir+"/subscribers_gen.go", buf.Bytes())
}

func generateServices(outDir, module string, imports []string) {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by gmcore; DO NOT EDIT.\n\n")
	buf.WriteString("package generated\n\n")
	buf.WriteString("import (\n")
	for _, imp := range imports {
		buf.WriteString(fmt.Sprintf("\t_ \"%s\"\n", imp))
	}
	buf.WriteString(")\n")
	writeGo(outDir+"/services_gen.go", buf.Bytes())
}

func readServicesYAML(path string) []string {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil
	}
	return parseServicesYAML(string(data))
}

func parseServicesYAML(content string) []string {
	var imports []string
	lines := strings.Split(content, "\n")
	inImports := false
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if trimmed == "imports:" {
			inImports = true
			continue
		}
		if inImports && strings.HasPrefix(trimmed, "- ") {
			imp := strings.TrimPrefix(trimmed, "- ")
			imports = append(imports, imp)
		}
		if inImports && !strings.HasPrefix(trimmed, "- ") && trimmed != "" {
			inImports = false
		}
	}
	return imports
}

func writeGo(path string, src []byte) {
	formatted, err := format.Source(src)
	if err != nil {
		fmt.Fprintf(os.Stderr, "format error in %s: %v\n", path, err)
		os.WriteFile(path, src, 0644)
		return
	}
	os.WriteFile(path, formatted, 0644)
}

func convertPath(path string) string {
	path = strings.ReplaceAll(path, "{", "(?P<")
	path = strings.ReplaceAll(path, "}", ">[^/]+)")
	return "^" + strings.Trim(path, "/") + "/?$"
}

func formatSlice(items []string) string {
	var quoted []string
	for _, p := range items {
		quoted = append(quoted, fmt.Sprintf("%q", p))
	}
	return "[]string{" + strings.Join(quoted, ", ") + "}"
}

func formatRoles(roles string) string {
	parts := strings.Split(roles, ",")
	var quoted []string
	for _, p := range parts {
		p = strings.TrimSpace(p)
		p = strings.Trim(p, `"`)
		p = strings.TrimSpace(p)
		if p != "" {
			quoted = append(quoted, fmt.Sprintf("%q", p))
		}
	}
	return strings.Join(quoted, ", ")
}

func formatMethods(methods string) string {
	parts := strings.Split(methods, ",")
	var quoted []string
	for _, p := range parts {
		p = strings.TrimSpace(p)
		quoted = append(quoted, fmt.Sprintf("%q", p))
	}
	return strings.Join(quoted, ", ")
}

func scan(dir string) ([]discoveredAnnotation, []string) {
	// ... same scan logic as before but without the annotation collector
	// reusing the scan function from the existing code
	var result []discoveredAnnotation
	var structs []string
	seen := make(map[string]bool)

	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, func(info os.FileInfo) bool {
		return strings.HasSuffix(info.Name(), ".go") && !strings.HasSuffix(info.Name(), "_test.go")
	}, parser.ParseComments)
	if err != nil {
		return result, structs
	}

	for _, pkg := range pkgs {
		for _, file := range pkg.Files {
			for _, decl := range file.Decls {
				genDecl, ok := decl.(*ast.GenDecl)
				if !ok || genDecl.Tok != token.TYPE {
					continue
				}
				for _, spec := range genDecl.Specs {
					ts, ok := spec.(*ast.TypeSpec)
					if !ok {
						continue
					}
					if _, ok := ts.Type.(*ast.StructType); ok {
						n := ts.Name.Name
						if n == "" || n[0] < 'A' || n[0] > 'Z' {
							continue
						}
						if !seen[n] {
							structs = append(structs, n)
							seen[n] = true
						}
					}
				}
			}

			for _, decl := range file.Decls {
				fd, ok := decl.(*ast.FuncDecl)
				if !ok || fd.Recv == nil || fd.Doc == nil {
					continue
				}
				baseName := strings.TrimPrefix(receiverType(fd.Recv.List[0].Type), "*")
				if !seen[baseName] {
					continue
				}
				target := annotations.AnnotationTarget{StructName: baseName, MethodName: fd.Name.Name}
				for _, c := range fd.Doc.List {
					name, args, ok := annotations.Parse(c.Text)
					if !ok {
						continue
					}
					result = append(result, discoveredAnnotation{
						Name:    name,
						Target:  target,
						Args:    args,
						Context: "method",
					})
				}
			}
		}
	}
	return result, structs
}

func receiverType(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.StarExpr:
		if ident, ok := t.X.(*ast.Ident); ok {
			return "*" + ident.Name
		}
	case *ast.Ident:
		return t.Name
	}
	return ""
}
